package com.darkfactor.platform.dsl.core;

public enum TraceLinkType {
  INITIATIVE_TO_EPIC,
  EPIC_TO_USER_STORY,
  USER_STORY_TO_ACCEPTANCE_CRITERION,
  USER_STORY_TO_WORKFLOW_STEP,
  WORKFLOW_STEP_TO_CAPABILITY,
  CAPABILITY_TO_SERVICE_CANDIDATE,
  USER_STORY_TO_DOMAIN_ENTITY,
  USER_STORY_TO_BUSINESS_RULE,
  INITIATIVE_TO_NFR,
  NFR_TO_ARCHITECTURE_CONCERN
}
